# Generated by Django 5.1.3 on 2025-01-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_restaurantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='order',
        ),
    ]
