# Generated by Django 5.1.3 on 2025-01-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_restaurantimage_options_restaurant_is_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='photo_count',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='total_width',
        ),
    ]
