# Generated by Django 5.1.3 on 2025-01-27 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_restaurant_is_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='furniture',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('served', 'Served')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.table'),
            preserve_default=False,
        ),
    ]
