# Generated by Django 5.1.3 on 2025-01-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='x_offset',
            new_name='x_position',
        ),
        migrations.RenameField(
            model_name='chair',
            old_name='y_offset',
            new_name='y_position',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.AddField(
            model_name='chair',
            name='height',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='chair',
            name='width',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='order',
            name='chair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.chair'),
            preserve_default=False,
        ),
    ]
