# Generated by Django 5.1.3 on 2025-01-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_x_offset_chair_x_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='x_position',
            new_name='x_offset',
        ),
        migrations.RenameField(
            model_name='chair',
            old_name='y_position',
            new_name='y_offset',
        ),
        migrations.RemoveField(
            model_name='chair',
            name='height',
        ),
        migrations.RemoveField(
            model_name='chair',
            name='width',
        ),
        migrations.RemoveField(
            model_name='order',
            name='chair',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.table'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emoji',
        ),
    ]
